[package]
name = "bevy_simple_prefs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_simple_prefs_derive = { path = "../bevy_simple_prefs_derive" }
bevy = { git = "https://github.com/bevyengine/bevy.git" }
web-sys = { version = "0.3", features = ["Window", "Storage"] }
serde = "1.0"
ron = "0.8"
