[package]
name = "bevy_simple_prefs_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false }
quote = "1.0"
syn = "2.0"

[lib]
proc-macro = true

[lints.rust]
missing_docs = "warn"

[lints.clippy]
type_complexity = "allow"
