[package]
name = "bevy_simple_prefs_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
quote = "1.0"
syn = "2.0"

[lib]
proc-macro = true
